name: Build and Push to ECR

# Trigger the workflow on push to main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Environment variables
env:
  AWS_REGION: eu-central-1
  ECR_REPOSITORY: ecs-cicd-lab-dev-java-app
  IMAGE_TAG: latest
  PROJECT_NAME: ecs-cicd-lab
  ENVIRONMENT: dev

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    # Required permissions for OIDC
    permissions:
      id-token: write
      contents: read

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Java 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      # Step 3: Run tests
      - name: Run tests
        run: mvn test --batch-mode --fail-at-end

      # Step 4: Build application
      - name: Build application
        run: mvn clean package -DskipTests=true --batch-mode

      # Step 5: Configure AWS credentials using OIDC
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ env.PROJECT_NAME }}-${{ env.ENVIRONMENT }}-github-actions-role
          role-session-name: GitHubActionsSession
          aws-region: ${{ env.AWS_REGION }}

      # Step 6: Login to Amazon ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # Step 7: Build Docker image
      - name: Build Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          COMMIT_HASH: ${{ github.sha }}
        run: |
          echo "Building Docker image..."
          
          # Build with both latest and commit hash tags
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:${COMMIT_HASH:0:7} .
          
          echo "Docker images built successfully:"
          docker images | grep $ECR_REPOSITORY

      # Step 8: Run security scan on Docker image (optional but recommended)
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
          format: 'sarif'
          output: 'trivy-results.sarif'
        continue-on-error: true

      # Step 9: Upload Trivy scan results to GitHub Security tab
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'
        continue-on-error: true

      # Step 10: Push Docker images to ECR
      - name: Push Docker images to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          COMMIT_HASH: ${{ github.sha }}
        run: |
          echo "Pushing Docker images to ECR..."
          
          # Push both tags
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:${COMMIT_HASH:0:7}
          
          echo "Images pushed successfully:"
          echo "Latest: $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
          echo "SHA: $ECR_REGISTRY/$ECR_REPOSITORY:${COMMIT_HASH:0:7}"

      # Step 11: Output image details
      - name: Output image details
        id: image-details
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          COMMIT_HASH: ${{ github.sha }}
        run: |
          echo "::notice::Docker image pushed to ECR"
          echo "::notice::Image URI: $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
          echo "::notice::Image SHA: $ECR_REGISTRY/$ECR_REPOSITORY:${COMMIT_HASH:0:7}"
          
          # Set outputs for potential use in subsequent jobs
          echo "image-uri=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
          echo "image-sha-uri=$ECR_REGISTRY/$ECR_REPOSITORY:${COMMIT_HASH:0:7}" >> $GITHUB_OUTPUT

      # Step 12: Clean up local Docker images to save space
      - name: Clean up
        if: always()
        run: |
          docker system prune -f
          docker image prune -af

  # Deploy job - Triggers CodePipeline after successful build
  deploy:
    name: Trigger Deployment
    runs-on: ubuntu-latest
    needs: build-and-push
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ env.PROJECT_NAME }}-${{ env.ENVIRONMENT }}-github-actions-role
          role-session-name: GitHubActionsDeploySession
          aws-region: ${{ env.AWS_REGION }}

      # Trigger CodePipeline manually (EventBridge should also trigger it automatically)
      - name: Trigger CodePipeline
        run: |
          PIPELINE_NAME="${{ env.PROJECT_NAME }}-${{ env.ENVIRONMENT }}-pipeline"
          
          echo "Triggering CodePipeline: $PIPELINE_NAME"
          
          # Start pipeline execution
          EXECUTION_ID=$(aws codepipeline start-pipeline-execution \
            --name $PIPELINE_NAME \
            --query 'pipelineExecutionId' \
            --output text)
          
          echo "Pipeline execution started with ID: $EXECUTION_ID"
          echo "::notice::CodePipeline execution started: $EXECUTION_ID"
          
          # Optional: Wait for pipeline to start and get initial status
          sleep 10
          aws codepipeline get-pipeline-execution \
            --pipeline-name $PIPELINE_NAME \
            --pipeline-execution-id $EXECUTION_ID \
            --query 'pipelineExecution.status' \
            --output text

      # Optional: Post deployment status to PR (if this was triggered by PR)
      - name: Comment on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const { ECR_REGISTRY } = process.env;
            const imageUri = `${ECR_REGISTRY}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🚀 **Docker Image Built Successfully**
            
              **Image URI:** \`${imageUri}\`
              **Commit:** ${context.sha.substring(0, 7)}
            
              The image has been pushed to ECR and is ready for deployment.`
            });